#!/usr/bin/env python3
"""Render the per-table CSVs from ``rq_tables.py`` into booktabs ``.tex`` tables.

The "script to tex table" half of the pipeline: a declarative spec registry
(``SPECS``) maps each ``reports/tex_src/*.csv`` to one ``reports/tex/*.tex``
file, choosing which columns to show, their headers and number precision, the
\\multicolumn group bands, the bolding rule, and the caption/label. Output drops
straight into the paper (copy ``reports/tex/*.tex`` into ``working/table`` and
``working/appendix``; see HOWTO-REGENERATE-RQ.md).

stdlib only; deterministic (re-running yields byte-identical .tex).

    python3 mini-src/rq_tables.py        # build the CSVs first
    python3 mini-src/csv_to_tex.py       # -> reports/tex/*.tex
"""

from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVAL = HERE.parent
TEX_SRC = EVAL / "reports" / "tex_src"
TEX_OUT = EVAL / "reports" / "tex"


# --------------------------------------------------------------------------- #
# Formatting
# --------------------------------------------------------------------------- #
def fmt(val, kind):
    if val in ("", None):
        return "--"
    if kind == "int":
        return str(round(float(val)))
    dp = 3 if kind == "f3" else 2
    s = f"{float(val):.{dp}f}"
    if s.startswith("0."):
        s = s[1:]
    elif s.startswith("-0."):
        s = "-" + s[2:]
    return s


def _num(val):
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def extrema(rows, cols):
    """{field: best_value} for columns flagged bold max/min (over non-empty cells)."""
    best = {}
    for c in cols:
        if not c.get("bold"):
            continue
        vals = [v for v in (_num(r.get(c["field"], "")) for r in rows) if v is not None]
        if vals:
            best[c["field"]] = max(vals) if c["bold"] == "max" else min(vals)
    return best


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render(spec):
    rows = list(csv.DictReader((TEX_SRC / spec["csv"]).open(encoding="utf-8")))
    labels = spec["labels"]
    cols = spec["cols"]
    nlab = len(labels)
    best = {} if spec.get("no_bold") else extrema(rows, cols)

    if "colspec" in spec:
        colspec = spec["colspec"]
    else:
        colspec = "@{}" + "l" * nlab + " " + "r" * len(cols) + "@{}"

    out = []
    out.append(f"% GENERATED by transarc-emp/mini-src/csv_to_tex.py from reports/tex_src/{spec['csv']}.")
    out.append("% Do not edit by hand: rerun rq_tables.py + csv_to_tex.py, then re-copy into the paper.")
    out.append("\\begin{table*}[t]" if spec.get("star") else "\\begin{table}[t]")
    out.append(f"\\caption{{{spec['caption']}}}")
    out.append(f"\\label{{{spec['label']}}}")
    out.append("\\centering" + spec.get("size", "\\small"))
    if spec.get("colsep"):
        out.append(f"\\setlength{{\\tabcolsep}}{{{spec['colsep']}}}")
    out.append(f"\\begin{{tabular}}{{{colspec}}}")
    out.append("\\toprule")

    # group band + cmidrules
    if spec.get("groups"):
        cells = [""] * nlab + [f"\\multicolumn{{{span}}}{{c}}{{{lab}}}" for lab, span in spec["groups"]]
        out.append(" & ".join(cells) + " \\\\")
        rules, start = [], nlab + 1
        for lab, span in spec["groups"]:
            if lab:
                rules.append(f"\\cmidrule(lr){{{start}-{start + span - 1}}}")
            start += span
        out.append("".join(rules))

    # column headers
    head = [lab["header"] for lab in labels] + [c["header"] for c in cols]
    out.append(" & ".join(head) + " \\\\")
    out.append("\\midrule")

    # body (group_by suppresses the repeated label and inserts \addlinespace per group)
    gb = next((i for i, lab in enumerate(labels) if lab.get("group_by")), None)
    prev = None
    for ri, r in enumerate(rows):
        if spec.get("midrule_before_last") and ri == len(rows) - 1:
            out.append("\\midrule")
        new_group = gb is not None and r[labels[gb]["field"]] != prev
        if new_group:
            if ri > 0:
                out.append("\\addlinespace[2pt]")
            prev = r[labels[gb]["field"]]
        cells = []
        for i, lab in enumerate(labels):
            v = r[lab["field"]]
            shown = lab.get("map", {}).get(v, v)
            if gb is not None and i == gb and not new_group:
                shown = ""
            cells.append(shown)
        for c in cols:
            v = r.get(c["field"], "")
            s = fmt(v, c["kind"])
            n = _num(v)
            if c["field"] in best and n is not None and abs(n - best[c["field"]]) < 1e-9:
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        out.append(" & ".join(cells) + " \\\\")

    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    if spec.get("footnote"):
        out.append(f"\\par\\smallskip\\footnotesize {spec['footnote']}")
    out.append("\\end{table*}" if spec.get("star") else "\\end{table}")

    text = "\n".join(out) + "\n"
    TEX_OUT.mkdir(parents=True, exist_ok=True)
    (TEX_OUT / spec["out"]).write_text(text, encoding="utf-8")
    print(f"[csv2tex] wrote {TEX_OUT / spec['out']}")


# --------------------------------------------------------------------------- #
# Column / label building blocks
# --------------------------------------------------------------------------- #
SYS_MAP = {"approach": "\\approach{}", "Artemis": "\\Artemis{}",
           "SWATTR": "SWATTR$^{\\dagger}$", "TransArC": "\\TransArc{}"}
BIGSYS_MAP = {"approach (GPT-5.4)": "\\approach{} (GPT-5.4)", "approach (Claude)": "\\approach{} (Claude)",
              "Artemis (GPT-5.4)": "\\Artemis{} (GPT-5.4)", "TransArC": "\\TransArc{}$^{\\dagger}$"}
VAR_MAP = {"Full": "Full", "Direct": "\\linkerB{} only",
           "Indirect": "\\linkerC{} only", "No knowledge": "No knowledge"}
BACKEND_MAP = {"openai": "GPT-5.4", "claude": "Claude"}

# the curated "whole suite" shown in the big tables (link P/R/F1 + file P/R/F1 + size-aware)
SUITE9 = [
    {"field": "doc_to_model_link_precision", "header": "P", "kind": "f2", "bold": "max"},
    {"field": "doc_to_model_link_recall", "header": "R", "kind": "f2", "bold": "max"},
    {"field": "doc_to_model_link_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "doc_to_code_file_precision", "header": "P", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_file_recall", "header": "R", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_file_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "doc_to_code_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_harmonic_component_f1", "header": "Harm", "kind": "f2", "bold": "max"},
]
SUITE9_GROUPS = [("doc-to-model (link \\fone)", 3), ("doc-to-code (file \\fone)", 3),
                 ("size-aware (doc-to-code)", 3)]


# --------------------------------------------------------------------------- #
# Spec registry
# --------------------------------------------------------------------------- #
SPECS = [
    # ---- RQ1 body ----
    {"csv": "rq1.csv", "out": "rq1-results.tex", "label": "tab:rq1", "size": "\\footnotesize", "colsep": "4pt",
     "caption": "RQ1 macro precision, recall, and \\fone\\ over the five projects on the GPT-5.4 backend "
                "(\\approach{} is \\texttt{s\\_linker21}, mean of three runs), for the doc-to-model "
                "(link \\fone) and doc-to-code (file \\fone) tasks. \\textbf{SWATTR}$^{\\dagger}$ is the "
                "doc-to-model baseline; \\TransArc{} is the doc-to-code baseline. Best \\fone\\ per task in "
                "bold. The Claude Sonnet backend and the per-project breakdown are in \\autoref{app:detailed}.",
     "labels": [{"field": "system", "header": "System", "map": SYS_MAP}],
     "groups": [("doc-to-model (link \\fone)", 3), ("doc-to-code (file \\fone)", 3)],
     "cols": [
         {"field": "dm_p", "header": "P", "kind": "f2"},
         {"field": "dm_r", "header": "R", "kind": "f2"},
         {"field": "dm_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_p", "header": "P", "kind": "f2"},
         {"field": "dc_r", "header": "R", "kind": "f2"},
         {"field": "dc_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
     ],
     "footnote": "$^{\\dagger}$SWATTR is the deterministic doc-to-model stage of \\TransArc{}; "
                 "\\TransArc{} has no standalone doc-to-model output."},

    # ---- RQ2 body (was fig:rq2-profile) ----
    {"csv": "rq2.csv", "out": "rq2-results.tex", "label": "tab:rq2", "colsep": "6pt",
     "caption": "RQ2: the size-aware suite of \\autoref{sec:metric:suite} on doc-to-code, GPT-5.4 backend "
                "(\\approach{} is \\texttt{s\\_linker21}, mean of three runs; the baselines single-shot). On the "
                "standard file \\fone\\ the systems are close; the gap widens on the size-aware tail. Best per "
                "column in bold. The per-project cells and the Claude Sonnet backend are in \\autoref{app:detailed}.",
     "labels": [{"field": "system", "header": "System", "map": SYS_MAP}],
     "cols": [
         {"field": "file_f1", "header": "File \\fone", "kind": "f3", "bold": "max"},
         {"field": "sentence_coverage", "header": "Sent.\\ cov.", "kind": "f2", "bold": "max"},
         {"field": "worst_component_f1", "header": "Worst\\ \\fone", "kind": "f2", "bold": "max"},
         {"field": "harmonic_component_f1", "header": "Harm.\\ \\fone", "kind": "f2", "bold": "max"},
     ]},

    # ---- RQ3 body confusion matrix ----
    {"csv": "rq3.csv", "out": "rq3-confusion.tex", "label": "tab:rq3-confusion",
     "colspec": "@{}l cc @{\\hskip 2.2em} cc@{}",
     "caption": "RQ3: confusion of the two evidence-grounded judges in \\fullVariant{} \\approach{} (GPT-5.4 "
                "backend, the canonical run). Each judge decides REJECT or KEEP for every link it inspects; rows "
                "give the link's true class. A good judge puts its mass on the helpful diagonal: REJECT false "
                "positives, KEEP true positives. Per-project counts and the Claude Sonnet backend are in "
                "\\autoref{app:detailed}.",
     "labels": [{"field": "true_class", "header": "True class"}],
     "groups": [("\\entValidator{}", 2), ("\\corefValidator{}", 2)],
     "cols": [
         {"field": "ent_reject", "header": "REJECT", "kind": "int"},
         {"field": "ent_keep", "header": "KEEP", "kind": "int"},
         {"field": "coref_reject", "header": "REJECT", "kind": "int"},
         {"field": "coref_keep", "header": "KEEP", "kind": "int"},
     ]},

    # ---- RQ3 Claude mirror (appendix) ----
    {"csv": "rq3_claude.csv", "out": "rq3-confusion-claude.tex", "label": "tab:rq3-confusion-claude",
     "colspec": "@{}l cc @{\\hskip 2.2em} cc@{}",
     "caption": "RQ3 judge confusion on the Claude Sonnet backend (cross-backend mirror of "
                "\\autoref{tab:rq3-confusion}). Same layout: each judge decides REJECT or KEEP per link, "
                "rows are the true class.",
     "labels": [{"field": "true_class", "header": "True class"}],
     "groups": [("\\entValidator{}", 2), ("\\corefValidator{}", 2)],
     "cols": [
         {"field": "ent_reject", "header": "REJECT", "kind": "int"},
         {"field": "ent_keep", "header": "KEEP", "kind": "int"},
         {"field": "coref_reject", "header": "REJECT", "kind": "int"},
         {"field": "coref_keep", "header": "KEEP", "kind": "int"},
     ]},

    # ---- RQ3 per-project judge decisions (appendix) ----
    {"csv": "rq3_perproject.csv", "out": "rq3-perproject.tex", "label": "tab:rq3-perproject",
     "midrule_before_last": True, "no_bold": True,
     "caption": "RQ3 per-project judge decisions on the GPT-5.4 backend (companion to "
                "\\autoref{tab:rq3-confusion}). FP rejected = false positives correctly removed (benefit); "
                "TP rejected = true positives wrongly removed (cost). Macro is the unweighted mean over the "
                "five projects.",
     "labels": [{"field": "project", "header": "Project"}],
     "groups": [("\\entValidator{}", 2), ("\\corefValidator{}", 2)],
     "cols": [
         {"field": "ent_fp_rej", "header": "FP rejected", "kind": "int"},
         {"field": "ent_tp_rej", "header": "TP rejected", "kind": "int"},
         {"field": "coref_fp_rej", "header": "FP rejected", "kind": "int"},
         {"field": "coref_tp_rej", "header": "TP rejected", "kind": "int"},
     ]},

    # ---- RQ4 body (was fig:rq4-ablation) ----
    {"csv": "rq4.csv", "out": "rq4-results.tex", "label": "tab:rq4", "colsep": "5pt",
     "caption": "RQ4 module ablation on the GPT-5.4 backend: the full approach and each module removed, with the "
                "doc-to-model macro \\fone\\ and the size-aware doc-to-code suite. Removing a linker or the "
                "knowledge module barely moves the standard scores but collapses the tail; the Uniq.\\ TP column "
                "counts the gold links a linker recovers that the other does not. Best per column in bold.",
     "labels": [{"field": "variant", "header": "Variant", "map": VAR_MAP}],
     "groups": [("doc-to-model", 1), ("doc-to-code (size-aware suite)", 4), ("", 1)],
     "cols": [
         {"field": "doc_to_model_macro_f1", "header": "Macro \\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_file_f1", "header": "File \\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_sentence_coverage", "header": "Sent.\\ cov.", "kind": "f2", "bold": "max"},
         {"field": "dc_worst_component_f1", "header": "Worst\\ \\fone", "kind": "f2", "bold": "max"},
         {"field": "dc_harmonic_component_f1", "header": "Harm.\\ \\fone", "kind": "f2", "bold": "max"},
         {"field": "unique_tps", "header": "Uniq.\\ TP", "kind": "int", "bold": "max"},
     ]},

    # ---- RQ1+RQ2 big table: average, both backends ----
    {"csv": "bigtable_rq12_avg.csv", "out": "big-table.tex", "label": "tab:detailed-macro", "star": True,
     "caption": "Full s21 comparison across the five projects, both backends, in one panel: the doc-to-model "
                "(link \\fone) and doc-to-code (file \\fone) standard rulers, and the size-aware suite of "
                "\\autoref{sec:metric:suite} (sentence coverage, worst-component \\fone, and harmonic-mean "
                "per-component \\fone; doc-to-code). \\approach{} is \\texttt{s\\_linker21} (mean of three runs); "
                "GPT-5.4 is the backend reported in the body, Claude Sonnet is the cross-backend mirror. Each "
                "system runs with its authors' released configuration. \\TransArc{}$^{\\dagger}$ uses SWATTR for "
                "the doc-to-model columns. Best per metric column in bold.",
     "labels": [{"field": "system", "header": "System", "map": BIGSYS_MAP}],
     "groups": SUITE9_GROUPS,
     "cols": SUITE9,
     "footnote": "$^{\\dagger}$The doc-to-model columns for \\TransArc{} are SWATTR, its deterministic "
                 "doc-to-model stage (\\TransArc{} has no standalone doc-to-model system). The size-aware "
                 "suite is defined on doc-to-code only."},

    # ---- RQ1+RQ2 big table: per project, both backends ----
    {"csv": "bigtable_rq12_perproject.csv", "out": "big-table-perproject.tex",
     "label": "tab:detailed-perproject", "star": True, "size": "\\footnotesize", "no_bold": True,
     "caption": "Per-project companion to \\autoref{tab:detailed-macro}: the doc-to-model (link \\fone) and "
                "doc-to-code (file \\fone) standard rulers and the size-aware suite, for every (system, project) "
                "on both backends. \\approach{} is \\texttt{s\\_linker21} (mean of three runs).",
     "labels": [{"field": "system", "header": "System", "map": BIGSYS_MAP, "group_by": True},
                {"field": "project", "header": "Project"}],
     "groups": SUITE9_GROUPS,
     "cols": SUITE9},

    # ---- RQ4 big table: average, both backends ----
    {"csv": "bigtable_rq4_avg.csv", "out": "rq4-bigtable.tex", "label": "tab:rq4-detailed", "star": True,
     "caption": "RQ4 module ablation on both backends: the doc-to-model macro \\fone, the doc-to-code file "
                "rulers, and the size-aware suite for the full approach and each module removed. Uniq.\\ TP is "
                "the count of gold links a linker recovers that the other does not. GPT-5.4 is the body backend, "
                "Claude Sonnet the mirror. Best per metric column in bold.",
     "labels": [{"field": "backend", "header": "Backend", "map": BACKEND_MAP, "group_by": True},
                {"field": "variant", "header": "Variant", "map": VAR_MAP}],
     "groups": [("doc-to-model", 1), ("doc-to-code (file \\fone)", 3), ("size-aware", 3), ("", 1)],
     "cols": [
         {"field": "doc_to_model_macro_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_file_precision", "header": "P", "kind": "f2", "bold": "max"},
         {"field": "dc_file_recall", "header": "R", "kind": "f2", "bold": "max"},
         {"field": "dc_file_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
         {"field": "dc_worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
         {"field": "dc_harmonic_component_f1", "header": "Harm", "kind": "f2", "bold": "max"},
         {"field": "unique_tps", "header": "Uniq.\\ TP", "kind": "int", "bold": "max"},
     ]},

    # ---- RQ4 big table: per project, both backends (doc-to-code suite) ----
    {"csv": "bigtable_rq4_perproject.csv", "out": "rq4-bigtable-perproject.tex",
     "label": "tab:rq4-perproject", "star": True, "size": "\\footnotesize", "no_bold": True,
     "caption": "Per-project companion to \\autoref{tab:rq4-detailed}: the doc-to-code file rulers and the "
                "size-aware suite for each RQ4 variant on every project, both backends. Doc-to-model macro "
                "\\fone\\ is reported per backend in \\autoref{tab:rq4-detailed} (not per project per variant).",
     "labels": [{"field": "backend", "header": "Backend", "map": BACKEND_MAP, "group_by": True},
                {"field": "variant", "header": "Variant", "map": VAR_MAP},
                {"field": "project", "header": "Project"}],
     "groups": [("doc-to-code (file \\fone)", 3), ("size-aware", 3)],
     "cols": [
         {"field": "dc_file_precision", "header": "P", "kind": "f2"},
         {"field": "dc_file_recall", "header": "R", "kind": "f2"},
         {"field": "dc_file_f1", "header": "\\fone", "kind": "f3"},
         {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2"},
         {"field": "dc_worst_component_f1", "header": "Worst", "kind": "f2"},
         {"field": "dc_harmonic_component_f1", "header": "Harm", "kind": "f2"},
     ]},
]


def main():
    for spec in SPECS:
        render(spec)
    print(f"\n[csv2tex] {len(SPECS)} tables written under {TEX_OUT}")


if __name__ == "__main__":
    main()
