#!/usr/bin/env python3
"""Render the per-table CSVs from ``rq_tables.py`` into booktabs ``.tex`` tables.

The "script to tex table" half of the pipeline: a declarative spec registry
(``SPECS``) maps each ``reports/tex_src/*.csv`` to one ``reports/tex/*.tex``
file, choosing which columns to show, their headers and number precision, the
\\multicolumn group bands, the bolding rule, and the caption/label. Output drops
straight into the paper (copy ``reports/tex/*.tex`` into ``working/table`` and
``working/appendix``; see HOWTO-REGENERATE-RQ.md).

stdlib only; deterministic (re-running yields byte-identical .tex).

    python3 mini-src/rq_tables.py        # build the CSVs first
    python3 mini-src/csv_to_tex.py       # -> reports/tex/*.tex
"""

from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVAL = HERE.parent
TEX_SRC = EVAL / "reports" / "tex_src"
TEX_OUT = EVAL / "reports" / "tex"


# --------------------------------------------------------------------------- #
# Formatting
# --------------------------------------------------------------------------- #
def fmt(val, kind):
    if val in ("", None):
        return "--"
    if kind == "int":
        return str(round(float(val)))
    if kind == "num":                     # integer if whole, else one decimal (mixed run + averaged counts)
        f = float(val)
        return str(round(f)) if abs(f - round(f)) < 1e-9 else f"{f:.1f}"
    if kind == "f1":                      # one decimal, keep the leading zero (averaged counts)
        return f"{float(val):.1f}"
    dp = 3 if kind == "f3" else 2
    s = f"{float(val):.{dp}f}"
    if s.startswith("0."):
        s = s[1:]
    elif s.startswith("-0."):
        s = "-" + s[2:]
    return s


def _num(val):
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def extrema(rows, cols):
    """{field: best_value} for columns flagged bold max/min (over non-empty cells)."""
    best = {}
    for c in cols:
        if not c.get("bold"):
            continue
        vals = [v for v in (_num(r.get(c["field"], "")) for r in rows) if v is not None]
        if vals:
            best[c["field"]] = max(vals) if c["bold"] == "max" else min(vals)
    return best


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render(spec):
    rows = list(csv.DictReader((TEX_SRC / spec["csv"]).open(encoding="utf-8")))
    labels = spec["labels"]
    cols = spec["cols"]
    nlab = len(labels)
    best = {} if spec.get("no_bold") else extrema(rows, cols)

    if "colspec" in spec:
        colspec = spec["colspec"]
    else:
        colspec = "@{}" + "l" * nlab + " " + "r" * len(cols) + "@{}"

    out = []
    out.append(f"% GENERATED by transarc-emp/mini-src/csv_to_tex.py from reports/tex_src/{spec['csv']}.")
    out.append("% Do not edit by hand: rerun rq_tables.py + csv_to_tex.py, then re-copy into the paper.")
    out.append("\\begin{table*}[t]" if spec.get("star") else "\\begin{table}[t]")
    out.append(f"\\caption{{{spec['caption']}}}")
    out.append(f"\\label{{{spec['label']}}}")
    out.append("\\centering" + spec.get("size", "\\small"))
    if spec.get("colsep"):
        out.append(f"\\setlength{{\\tabcolsep}}{{{spec['colsep']}}}")
    if spec.get("fit"):
        width = "\\textwidth" if spec.get("star") else "\\columnwidth"
        out.append("\\adjustbox{max width=" + width + "}{")
    tabularx = spec.get("tabularx")       # e.g. "\\columnwidth": stretch to that width
    if tabularx:
        out.append(f"\\begin{{tabularx}}{{{tabularx}}}{{{colspec}}}")
    else:
        out.append(f"\\begin{{tabular}}{{{colspec}}}")
    out.append("\\toprule")

    # group band + cmidrules
    if spec.get("groups"):
        cells = [""] * nlab + [f"\\multicolumn{{{span}}}{{c}}{{{lab}}}" for lab, span in spec["groups"]]
        out.append(" & ".join(cells) + " \\\\")
        rules, start = [], nlab + 1
        for lab, span in spec["groups"]:
            if lab:
                rules.append(f"\\cmidrule(lr){{{start}-{start + span - 1}}}")
            start += span
        out.append("".join(rules))

    # column headers
    head = [lab["header"] for lab in labels] + [c["header"] for c in cols]
    out.append(" & ".join(head) + " \\\\")
    out.append("\\midrule")

    # body. Each label flagged group_by blanks when its value repeats the row above.
    # \addlinespace separates blocks: the tuple of fields in ``block_by`` if given,
    # else the group_by fields. ``summary`` (e.g. project == "Average") bolds that row.
    gb_fields = [lab["field"] for lab in labels if lab.get("group_by")]
    block_fields = spec.get("block_by") or gb_fields
    summary = spec.get("summary")
    prev_block = None
    prev_vals = {}
    for ri, r in enumerate(rows):
        if spec.get("midrule_before_last") and ri == len(rows) - 1:
            out.append("\\midrule")
        block_key = tuple(r[f] for f in block_fields) if block_fields else None
        if block_key is not None and prev_block is not None and block_key != prev_block:
            out.append("\\addlinespace[2pt]")
        prev_block = block_key
        is_summary = summary is not None and r.get(summary["field"]) == summary["value"]
        # summary_label: force this label to show (bold) on the summary row even when
        # its group_by value repeats — it names the block the summary belongs to.
        summary_label = spec.get("summary_label")
        cells = []
        for lab in labels:
            v = r[lab["field"]]
            shown = lab.get("map", {}).get(v, v)
            repeats = lab.get("group_by") and prev_vals.get(lab["field"]) == v
            if repeats and not (is_summary and lab["field"] == summary_label):
                shown = ""
            if is_summary and shown:
                shown = f"\\textbf{{{shown}}}"
            cells.append(shown)
        for c in cols:
            v = r.get(c["field"], "")
            s = fmt(v, c["kind"])
            n = _num(v)
            if c["field"] in best and n is not None and abs(n - best[c["field"]]) < 1e-9:
                s = f"\\textbf{{{s}}}"
            elif is_summary and s != "--":
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        out.append(" & ".join(cells) + " \\\\")
        for lab in labels:
            prev_vals[lab["field"]] = r[lab["field"]]

    out.append("\\bottomrule")
    out.append("\\end{tabularx}" if tabularx else "\\end{tabular}")
    if spec.get("fit"):
        out.append("}")
    if spec.get("footnote"):
        out.append(f"\\par\\smallskip\\footnotesize {spec['footnote']}")
    out.append("\\end{table*}" if spec.get("star") else "\\end{table}")

    text = "\n".join(out) + "\n"
    TEX_OUT.mkdir(parents=True, exist_ok=True)
    (TEX_OUT / spec["out"]).write_text(text, encoding="utf-8")
    print(f"[csv2tex] wrote {TEX_OUT / spec['out']}")


# --------------------------------------------------------------------------- #
# Column / label building blocks
# --------------------------------------------------------------------------- #
SYS_MAP = {"approach": "\\approach{}", "Artemis": "\\Artemis{}",
           "SWATTR": "SWATTR$^{\\dagger}$", "TransArC": "\\TransArc{}"}
BIGSYS_MAP = {"approach (GPT-5.4)": "\\approach{} (GPT-5.4)", "approach (Claude)": "\\approach{} (Claude)",
              "Artemis (GPT-5.4)": "\\Artemis{} (GPT-5.4)", "TransArC": "\\TransArc{}$^{\\dagger}$"}
VAR_MAP = {"Full": "Full", "Direct": "\\linkerB{} only",
           "Indirect": "\\linkerC{} only", "No knowledge": "No knowledge"}
BACKEND_MAP = {"openai": "GPT-5.4", "claude": "Claude"}
RUN_MAP = {"run1": "Run 1", "run2": "Run 2", "run3": "Run 3", "average": "Avg", "single": "--"}

# the curated "whole suite" shown in the big tables (link P/R/F1 + file P/R/F1 + size-aware)
SUITE9 = [
    {"field": "doc_to_model_link_precision", "header": "P", "kind": "f2", "bold": "max"},
    {"field": "doc_to_model_link_recall", "header": "R", "kind": "f2", "bold": "max"},
    {"field": "doc_to_model_link_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "doc_to_model_silent_failure_mass", "header": "SFM", "kind": "f1", "bold": "min"},
    {"field": "doc_to_code_file_precision", "header": "P", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_file_recall", "header": "R", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_file_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "doc_to_code_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
    {"field": "doc_to_code_harmonic_component_f1", "header": "Harm", "kind": "f2", "bold": "max"},
]
SUITE9_GROUPS = [("doc-model (link \\fone)", 4), ("doc-code (link \\fone)", 3),
                 ("size-aware (doc-code)", 3)]

# Same suite without the doc-model SFM column: the per-run big table reports SFM in the
# body RQ2 + per-project detailed tables instead, so it is omitted here (co-author design).
SUITE_NOSFM = [c for c in SUITE9 if c["field"] != "doc_to_model_silent_failure_mass"]
SUITE_NOSFM_GROUPS = [("doc-model (link \\fone)", 3), ("doc-code (link \\fone)", 3),
                      ("size-aware (doc-code)", 3)]


# --------------------------------------------------------------------------- #
# Spec registry
# --------------------------------------------------------------------------- #
SPECS = [
    # ---- RQ1 body ----
    {"csv": "rq1.csv", "out": "rq1-results.tex", "label": "tab:rq1", "size": "%\\footnotesize", "colsep": "4pt",
     "colspec": "l ZZZZZZ", "tabularx": "\\columnwidth",
     "caption": "RQ1 macro precision, recall, and \\fone\\ on the GPT-5.4 backend.",
     "labels": [{"field": "system", "header": "System", "map": SYS_MAP}],
     "groups": [("doc-model (link \\fone)", 3), ("doc-code (link \\fone)", 3)],
     "cols": [
         {"field": "dm_p", "header": "P", "kind": "f2"},
         {"field": "dm_r", "header": "R", "kind": "f2"},
         {"field": "dm_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_p", "header": "P", "kind": "f2"},
         {"field": "dc_r", "header": "R", "kind": "f2"},
         {"field": "dc_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
     ],
     "footnote": "$^{\\dagger}$SWATTR is the deterministic doc-model stage of \\TransArc{}; "
                 "\\TransArc{} has no standalone doc-model output."},

    # ---- RQ2 body (was fig:rq2-profile) ----
    {"csv": "rq2.csv", "out": "rq2-results.tex", "label": "tab:rq2", "colsep": "3pt",
     "colspec": "@{}l ZZZZZZZ@{}", "tabularx": "\\columnwidth", "fit": True,
     "caption": "RQ2 size-aware suite, both tasks: reference \\fone\\ with sentence "
                "coverage (Cov) and the size-aware metrics on each task. GPT-5.4 backend.",
     "labels": [{"field": "system", "header": "System", "map": SYS_MAP}],
     "groups": [("doc-model (link \\fone)", 3), ("doc-code (link \\fone)", 4)],
     "cols": [
         {"field": "dm_link_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dm_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
         {"field": "silent_failure_mass", "header": "SFM\\%", "kind": "f1", "bold": "min"},
         {"field": "dc_file_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
         {"field": "worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
         {"field": "harmonic_component_f1", "header": "Harm.", "kind": "f2", "bold": "max"},
     ]},

    # ---- RQ3 body confusion matrix (mean of 3 runs) ----
    {"csv": "rq3.csv", "out": "rq3-confusion.tex", "label": "tab:rq3-confusion",
     "colspec": "l YY @{\\hskip 2.2em} YY", "tabularx": "\\columnwidth",
     "caption": "RQ3 judge confusion on the GPT-5.4 backend, averaged over the three runs.",
     "labels": [{"field": "true_class", "header": "True class"}],
     "groups": [("\\entValidator{}", 2), ("\\corefValidator{}", 2)],
     "cols": [
         {"field": "ent_reject", "header": "REJECT", "kind": "f1"},
         {"field": "ent_keep", "header": "KEEP", "kind": "f1"},
         {"field": "coref_reject", "header": "REJECT", "kind": "f1"},
         {"field": "coref_keep", "header": "KEEP", "kind": "f1"},
     ]},

    # ---- RQ3 confusion, both backends, each run + the average in ONE table (appendix) ----
    {"csv": "rq3_runs.csv", "out": "rq3-runs.tex", "label": "tab:rq3-runs", "no_bold": True,
     "colspec": "@{}lll cc @{\\hskip 2.2em} cc@{}",
     "block_by": ["backend", "run"], "summary": {"field": "run", "value": "average"},
     "caption": "RQ3 judge confusion per run and averaged, both backends "
                "(the runs behind body \\autoref{tab:rq3-confusion}).",
     "labels": [{"field": "backend", "header": "Backend", "map": BACKEND_MAP, "group_by": True},
                {"field": "run", "header": "Run", "map": RUN_MAP, "group_by": True},
                {"field": "true_class", "header": "True class"}],
     "groups": [("\\entValidator{}", 2), ("\\corefValidator{}", 2)],
     "cols": [
         {"field": "ent_reject", "header": "REJECT", "kind": "num"},
         {"field": "ent_keep", "header": "KEEP", "kind": "num"},
         {"field": "coref_reject", "header": "REJECT", "kind": "num"},
         {"field": "coref_keep", "header": "KEEP", "kind": "num"},
     ]},

    # ---- RQ4 body (was fig:rq4-ablation) ----
    {"csv": "rq4.csv", "out": "rq4-results.tex", "label": "tab:rq4", "size": "%\\footnotesize",
     "colsep": "3pt", "fit": True, "colspec": "l ZZZZZ", "tabularx": "\\columnwidth",
     "caption": "RQ4 module ablation on the GPT-5.4 backend.",
     "labels": [{"field": "variant", "header": "Variant", "map": VAR_MAP}],
     "groups": [("doc-model", 1), ("doc-code (size-aware)", 4)],
     "cols": [
         {"field": "doc_to_model_macro_f1", "header": "Macro\\ \\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_file_f1", "header": "File\\ \\fone", "kind": "f3", "bold": "max"},
         {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
         {"field": "dc_worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
         {"field": "dc_harmonic_component_f1", "header": "Harm", "kind": "f2", "bold": "max"},
     ]},

    # ---- RQ1+RQ2 big table: per project + per-system Average row, both backends ----
    {"csv": "bigtable_rq12_perproject.csv", "out": "big-table-perproject.tex",
     "label": "tab:detailed-perproject", "star": True, "size": "\\footnotesize", "no_bold": True,
     "summary": {"field": "project", "value": "Average"},
     "caption": "Full s21 comparison per project, with the five-project Average per system, both backends.",
     "labels": [{"field": "system", "header": "System", "map": BIGSYS_MAP, "group_by": True},
                {"field": "project", "header": "Project"}],
     "groups": SUITE9_GROUPS,
     "cols": SUITE9,
     "footnote": "$^{\\dagger}$The doc-model columns for \\TransArc{} are SWATTR, its deterministic "
                 "doc-model stage (\\TransArc{} has no standalone doc-model system). The size-aware "
                 "(doc-code) suite is Cov/Worst/Harm; the doc-model Silent-Failure Mass (SFM) sits "
                 "with the doc-model columns."},

    # ---- RQ1+RQ2 big table: per run + the average, both backends (SFM omitted here) ----
    {"csv": "bigtable_rq12_perrun.csv", "out": "big-table-perrun.tex",
     "label": "tab:detailed-perrun", "star": True, "size": "\\footnotesize", "no_bold": True,
     "summary": {"field": "run", "value": "average"},
     "caption": "Full s21 comparison per run for \\approach{} (stochastic; the baselines are "
                "deterministic, one run), both backends, five-project average.",
     "labels": [{"field": "system", "header": "System", "map": BIGSYS_MAP, "group_by": True},
                {"field": "run", "header": "Run", "map": RUN_MAP}],
     "groups": SUITE_NOSFM_GROUPS,
     "cols": SUITE_NOSFM,
     "footnote": "$^{\\dagger}$The doc-model columns for \\TransArc{} are SWATTR, its deterministic "
                 "doc-model stage (\\TransArc{} has no standalone doc-model system). The size-aware "
                 "columns shown here are the doc-code \\fone-tail (worst/harmonic); SFM is the "
                 "doc-model member, reported in \\autoref{tab:rq2} and \\autoref{tab:detailed-perproject}."},

    # ---- RQ4 big table: per project + per-variant Average row, both backends ----
    {"csv": "bigtable_rq4_perproject.csv", "out": "rq4-bigtable-perproject.tex",
     "label": "tab:rq4-perproject", "star": True, "size": "\\footnotesize", "no_bold": True,
     "block_by": ["backend", "variant"], "summary": {"field": "project", "value": "Average"},
     "summary_label": "variant",
     "caption": "RQ4 module ablation per project, with the per-variant average, both backends.",
     "labels": [{"field": "backend", "header": "Backend", "map": BACKEND_MAP, "group_by": True},
                {"field": "variant", "header": "Variant", "map": VAR_MAP, "group_by": True},
                {"field": "project", "header": "Project"}],
     "groups": [("doc-model (link \\fone)", 3), ("doc-code (link \\fone)", 3), ("size-aware", 3)],
     "cols": [
         {"field": "dm_link_precision", "header": "P", "kind": "f2"},
         {"field": "dm_link_recall", "header": "R", "kind": "f2"},
         {"field": "dm_link_f1", "header": "\\fone", "kind": "f3"},
         {"field": "dc_file_precision", "header": "P", "kind": "f2"},
         {"field": "dc_file_recall", "header": "R", "kind": "f2"},
         {"field": "dc_file_f1", "header": "\\fone", "kind": "f3"},
         {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2"},
         {"field": "dc_worst_component_f1", "header": "Worst", "kind": "f2"},
         {"field": "dc_harmonic_component_f1", "header": "Harm", "kind": "f2"},
     ]},
]


# ---- RQ4 per-run aggregate tables: one per run + the average (both backends x variants) ----
_RQ4_RUN_GROUPS = [("doc-model", 1), ("doc-code (link \\fone)", 3), ("size-aware", 3)]
_RQ4_RUN_COLS = [
    {"field": "doc_to_model_macro_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "dc_file_precision", "header": "P", "kind": "f2", "bold": "max"},
    {"field": "dc_file_recall", "header": "R", "kind": "f2", "bold": "max"},
    {"field": "dc_file_f1", "header": "\\fone", "kind": "f3", "bold": "max"},
    {"field": "dc_sentence_coverage", "header": "Cov", "kind": "f2", "bold": "max"},
    {"field": "dc_worst_component_f1", "header": "Worst", "kind": "f2", "bold": "max"},
    {"field": "dc_harmonic_component_f1", "header": "Harm", "kind": "f2", "bold": "max"},
]
SPECS += [
    {"csv": csv, "out": out, "label": label, "star": True, "caption": caption,
     "labels": [{"field": "backend", "header": "Backend", "map": BACKEND_MAP, "group_by": True},
                {"field": "variant", "header": "Variant", "map": VAR_MAP}],
     "groups": _RQ4_RUN_GROUPS, "cols": _RQ4_RUN_COLS}
    for csv, out, label, caption in [
        ("rq4_run1.csv", "rq4-run1.tex", "tab:rq4-run1", "RQ4 module ablation, run 1, both backends."),
        ("rq4_run2.csv", "rq4-run2.tex", "tab:rq4-run2", "RQ4 module ablation, run 2, both backends."),
        ("rq4_run3.csv", "rq4-run3.tex", "tab:rq4-run3", "RQ4 module ablation, run 3, both backends."),
        ("rq4_runavg.csv", "rq4-runavg.tex", "tab:rq4-runavg",
         "RQ4 module ablation, average of the three runs, both backends."),
    ]
]


def main():
    for spec in SPECS:
        render(spec)
    print(f"\n[csv2tex] {len(SPECS)} tables written under {TEX_OUT}")


if __name__ == "__main__":
    main()
