#!/usr/bin/env python3
"""Sync the generated paper tables into the alinker-paper repo, and guard against drift.

Single source of truth for the engine -> paper bridge (replaces the hand ``cp`` blocks in
HOWTO-REGENERATE-RQ.md). The RQ table set is derived from ``csv_to_tex.SPECS``, so it tracks
table adds/removes automatically: each spec's rendered ``reports/tex/<out>.tex`` is copied into
the paper, together with its ``reports/tex_src/<csv>`` companion (renamed to ``<out-stem>.csv``).
The four body tables land in ``<paper>/table``; every other table in ``<paper>/appendix``.
``gold_concentration.{tex,csv}`` (the OUT-02 inequality artifacts) is synced too.

    python3 mini-src/sync_paper.py             # copy generated files into the paper
    python3 mini-src/sync_paper.py --check      # byte-diff only; exit 1 on drift (CI guard)
    python3 mini-src/sync_paper.py --only rq    # restrict to the RQ tables (skip gold)
    PAPER_DIR=/path/to/alinker-paper python3 mini-src/sync_paper.py
    python3 mini-src/sync_paper.py /path/to/alinker-paper

Run the generators first (``rq_tables.py`` + ``csv_to_tex.py``); ``--check`` compares the
already-generated files and does not rebuild the RQ tables. Exit 0 = done / in sync;
1 = drift (``--check``); 2 = paper dir not found.
"""
from __future__ import annotations

import argparse
import difflib
import shutil
import sys
from pathlib import Path

import csv_to_tex as c2t

HERE = Path(__file__).resolve().parent          # .../transarc-emp/mini-src
EVAL = HERE.parent                              # .../transarc-emp

# The four body tables; everything else generated by csv_to_tex goes to the appendix.
BODY = {"rq1-results.tex", "rq2-results.tex", "rq3-confusion.tex", "rq4-results.tex"}


def rq_pairs():
    """(generated_path, paper_subdir, paper_filename) for every RQ .tex + its companion .csv."""
    for spec in c2t.SPECS:
        out = spec["out"]                                       # e.g. big-table-perproject.tex
        subdir = "table" if out in BODY else "appendix"
        yield c2t.TEX_OUT / out, subdir, out                    # rendered table
        yield c2t.TEX_SRC / spec["csv"], subdir, Path(out).stem + ".csv"  # reviewable companion


def gold_pairs(regenerate=True):
    """(generated_path, 'table', paper_filename) for the OUT-02 gold_concentration pair.

    Imported lazily so RQ-only syncs do not depend on the inequality engine / benchmark."""
    sys.path.insert(0, str(EVAL / "mini-inequality"))
    import motivation as mot
    if regenerate:
        mot.write_out02_concentration()
    yield mot.REPORTS / "out02_concentration.tex", "table", "gold_concentration.tex"
    yield mot.REPORTS / "out02_concentration.csv", "table", "gold_concentration.csv"


def plan(only, regenerate_gold):
    items = []
    if only in ("all", "rq"):
        items += list(rq_pairs())
    if only in ("all", "gold"):
        items += list(gold_pairs(regenerate=regenerate_gold))
    return items


def locate_paper_dir(arg=None):
    candidates = [
        arg,
        # sibling repo layout: .../transarc-emp -> .../alinker-paper
        EVAL.parent / "alinker-paper",
        # mono symlink lens, if present
        EVAL.parent / "mono" / "working",
    ]
    for c in candidates:
        if c and (Path(c) / "table").is_dir() and (Path(c) / "appendix").is_dir():
            return Path(c)
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description="Sync / check the paper tables.")
    ap.add_argument("paper_dir", nargs="?", help="alinker-paper root (else env PAPER_DIR / autodetect)")
    ap.add_argument("--check", action="store_true", help="diff only; exit 1 on drift")
    ap.add_argument("--only", choices=("all", "rq", "gold"), default="all")
    args = ap.parse_args(argv)

    import os
    paper = locate_paper_dir(args.paper_dir or os.environ.get("PAPER_DIR"))
    if paper is None:
        print("ERROR: could not locate the alinker-paper root (needs table/ + appendix/).")
        print("Pass it as an argument or set PAPER_DIR=...")
        return 2

    items = plan(args.only, regenerate_gold=True)
    drift = changed = 0
    for gen, subdir, name in items:
        dest = paper / subdir / name
        if not gen.is_file():
            print(f"MISSING generated source: {gen}  (run rq_tables.py + csv_to_tex.py)")
            drift += 1
            continue
        if args.check:
            old = dest.read_text() if dest.is_file() else ""
            new = gen.read_text()
            if old == new:
                continue
            drift += 1
            print(f"\nDRIFT: {dest} differs from {gen}")
            sys.stdout.writelines(difflib.unified_diff(
                old.splitlines(keepends=True), new.splitlines(keepends=True),
                fromfile=str(dest), tofile=str(gen)))
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(gen, dest)
            changed += 1

    if args.check:
        print(f"\n{'DRIFT' if drift else 'IN SYNC'}: {drift} file(s) out of date." if drift
              else f"IN SYNC: all {len(items)} paper file(s) match the generated output.")
        return 1 if drift else 0
    print(f"synced {changed} file(s) into {paper}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
