#!/usr/bin/env python3
"""RQ4 main-body + appendix figure/table generator.

Implements REQ-V263-04 / REQ-V263-05 (D-04, D-05, D-06). See
agent-linker/.planning/phases/43-replay-s-linker19-checkpoints-for-paper-rq1-rq4-eval/43-CONTEXT.md.

Reads Plan 02 CSVs at:
    <csv-root>/<backend>/<project>/rq4.csv         (2 linker rows: Entity, Coref)
    <csv-root>/<backend>/<project>/rq4_upset.csv   (3 cell rows: only_E, both, only_C)

Emits four TeX files:
    main:     <main>/table/rq4-agents.tex      (booktabs, 2 linker rows + overlap footer)
              <main>/figures/rq4-upset.tex     (2-set / 3-cell UpSet TikZ)
    appendix: <appendix>/rq4-agents-gpt.tex
              <appendix>/rq4-upset-gpt.tex

Main body = Claude. Appendix = GPT-5.4 (openai). (D-04)
Two-linker table per D-05; 3-cell UpSet per D-06.

Stdlib only.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List

PROJECTS = ["mediastore", "teastore", "teammates", "bigbluebutton", "jabref"]
BACKENDS = ["claude", "openai"]

BACKEND_DISPLAY = {"claude": "Claude", "openai": "GPT-5.4"}


# ---------------------------------------------------------------------------
# CSV ingestion
# ---------------------------------------------------------------------------
def _read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def aggregate_backend_linker(csv_root: Path, backend: str) -> Dict[str, Dict[str, float]]:
    """Aggregate rq4.csv across 5 projects.

    Returns dict keyed by linker name (Entity, Coref) with:
        tps_caught_sum, unique_tps_sum, fps_sum (int sums)
        delta_f1_mean (macro mean of per-project delta)
        n (project count)
    """
    by_linker: Dict[str, Dict[str, float]] = {}
    for project in PROJECTS:
        path = csv_root / backend / project / "rq4.csv"
        if not path.exists():
            continue
        for row in _read_csv(path):
            l = row["linker"]
            entry = by_linker.setdefault(
                l,
                {
                    "tps_caught_sum": 0,
                    "unique_tps_sum": 0,
                    "fps_sum": 0,
                    "delta_f1_sum": 0.0,
                    "n": 0,
                },
            )
            entry["tps_caught_sum"] += int(row["tps_caught"])
            entry["unique_tps_sum"] += int(row["unique_tps"])
            entry["fps_sum"] += int(row["fps"])
            entry["delta_f1_sum"] += float(row["delta_f1_if_removed"])
            entry["n"] += 1
    result: Dict[str, Dict[str, float]] = {}
    for l, e in by_linker.items():
        n = max(int(e["n"]), 1)
        result[l] = {
            "tps_caught": int(e["tps_caught_sum"]),
            "unique_tps": int(e["unique_tps_sum"]),
            "fps": int(e["fps_sum"]),
            "delta_f1_mean": e["delta_f1_sum"] / n,
            "n": n,
        }
    return result


def aggregate_backend_upset(csv_root: Path, backend: str) -> Dict[str, int]:
    """Aggregate rq4_upset.csv across 5 projects (sum per cell)."""
    by_cell: Dict[str, int] = {"only_E": 0, "both": 0, "only_C": 0}
    for project in PROJECTS:
        path = csv_root / backend / project / "rq4_upset.csv"
        if not path.exists():
            continue
        for row in _read_csv(path):
            cell = row["cell"]
            by_cell[cell] = by_cell.get(cell, 0) + int(row["count"])
    return by_cell


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------
def _fmt_dF1(value: float) -> str:
    return f"{value:+.3f}"


# ---------------------------------------------------------------------------
# TeX emitters
# ---------------------------------------------------------------------------
TABLE_HEADER_COMMENT = (
    "% RQ4: per-linker contribution table (Phase 43 Plan 04, REQ-V263-04 / D-05).\n"
    "% Generated by transarc-emp/src/paper/rq4_table.py from\n"
    "% agent-linker/results/v2.6.3/<backend>/<project>/rq4.csv + rq4_upset.csv.\n"
    "% Macro labels (D-10) defined in writing/working/abbrev.tex.\n"
)

FIGURE_HEADER_COMMENT = (
    "% RQ4 2-set / 3-cell UpSet figure (Phase 43 Plan 04, REQ-V263-04 / D-06).\n"
    "% Generated by transarc-emp/src/paper/rq4_table.py.\n"
    "% Cells: only \\linkerB{}, both, only \\linkerC{}.\n"
)


def render_rq4_table(
    linkers: Dict[str, Dict[str, float]],
    overlap_value: int,
    backend: str,
    output_path: Path,
    table_label: str,
) -> None:
    """Render the 2-linker booktabs table with an overlap-TP footer."""
    backend_label = BACKEND_DISPLAY.get(backend, backend)

    e = linkers.get("Entity", {"tps_caught": 0, "unique_tps": 0, "fps": 0, "delta_f1_mean": 0.0})
    c = linkers.get("Coref", {"tps_caught": 0, "unique_tps": 0, "fps": 0, "delta_f1_mean": 0.0})

    is_appendix = table_label.endswith("-gpt")
    if is_appendix:
        caption = (
            "Per-linker contribution from \\fullVariant{} \\approach{} ("
            + backend_label
            + " backend, appendix mirror, see \\autoref{tab:rq4-agents}). "
            "\\emph{TPs caught} = gold links emitted by this linker (linkers may share TPs); "
            "\\emph{Unique TPs} = gold links no other linker emitted; "
            "\\emph{dF1 if removed} compares against \\fullVariant{}."
        )
    else:
        caption = (
            "Per-linker contribution from \\fullVariant{} \\approach{} ("
            + backend_label
            + " backend). \\emph{TPs caught} = gold links emitted by this linker "
            "(linkers may share TPs); \\emph{Unique TPs} = gold links no other linker "
            "emitted; \\emph{dF1 if removed} compares against \\fullVariant{}."
        )

    lines: List[str] = []
    lines.append(TABLE_HEADER_COMMENT.rstrip())
    lines.append("\\begin{table}[t]")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{table_label}}}")
    lines.append("\\centering\\small")
    lines.append("\\begin{tabular}{@{}lrrrr@{}}")
    lines.append("\\toprule")
    lines.append("Agent & TPs caught & Unique TPs & FPs & $\\Delta$\\fone\\ if removed \\\\")
    lines.append("\\midrule")
    lines.append(
        "\\linkerB{} & "
        f"{int(e['tps_caught'])} & {int(e['unique_tps'])} & {int(e['fps'])} & "
        f"{_fmt_dF1(float(e['delta_f1_mean']))} \\\\"
    )
    lines.append(
        "\\linkerC{} & "
        f"{int(c['tps_caught'])} & {int(c['unique_tps'])} & {int(c['fps'])} & "
        f"{_fmt_dF1(float(c['delta_f1_mean']))} \\\\"
    )
    lines.append("\\midrule")
    lines.append(
        "$|\\linkerB{} \\cap \\linkerC{} \\cap \\text{gold}|$ & "
        f"{int(overlap_value)} & -- & -- & -- \\\\"
    )
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def render_rq4_upset(
    upset_cells: Dict[str, int],
    backend: str,
    output_path: Path,
    figure_label: str,
) -> None:
    """Render the 2-set / 3-cell UpSet TikZ figure."""
    backend_label = BACKEND_DISPLAY.get(backend, backend)

    only_e = int(upset_cells.get("only_E", 0))
    both = int(upset_cells.get("both", 0))
    only_c = int(upset_cells.get("only_C", 0))

    max_ct = max(only_e, both, only_c, 1)  # avoid zero division in TikZ

    is_appendix = figure_label.endswith("-gpt")
    if is_appendix:
        caption = (
            "UpSet-style summary of true-positive set membership across the two "
            "linker agents in \\fullVariant{} \\approach{} ("
            + backend_label
            + " backend, appendix mirror; see \\autoref{fig:rq4-upset}). "
            "Dots in a column mark the linker(s) whose TP sets intersect; "
            "bar height = number of gold links in that intersection."
        )
    else:
        caption = (
            "UpSet-style summary of true-positive set membership across the two "
            "linker agents in \\fullVariant{} \\approach{} ("
            + backend_label
            + " backend). Dots in a column mark the linker(s) whose TP sets intersect; "
            "bar height = number of gold links in that intersection."
        )

    lines: List[str] = []
    lines.append(FIGURE_HEADER_COMMENT.rstrip())
    lines.append("\\begin{figure}[t]")
    lines.append("\\centering")
    lines.append("\\begin{tikzpicture}[")
    lines.append("  bar/.style={fill=darkblue,draw=black!70},")
    lines.append("  dot/.style={circle,fill=black,inner sep=1.4pt},")
    lines.append("  no-dot/.style={circle,draw=black!30,fill=white,inner sep=1.4pt},")
    lines.append("  connect/.style={thick,black},")
    lines.append("  label/.style={font=\\scriptsize,anchor=east},")
    lines.append("  axn/.style={font=\\tiny,gray!60},")
    lines.append("]")
    lines.append(f"\\def\\cw{{0.6}}\\def\\bh{{2.0}}\\def\\rh{{0.30}}\\def\\maxct{{{max_ct}}}")
    lines.append("")
    lines.append("% --- top bar chart (3 cells) ---")
    lines.append("\\foreach \\col/\\ct/\\lbl in {%")
    lines.append(f"  0/{only_e}/{{only \\linkerB{{}}}},%")
    lines.append(f"  1/{both}/{{both}},%")
    lines.append(f"  2/{only_c}/{{only \\linkerC{{}}}}%")
    lines.append("} {")
    lines.append("  \\pgfmathsetmacro{\\bhc}{\\bh * \\ct / \\maxct}")
    lines.append("  \\draw[bar] ({\\cw*\\col + 0.15*\\cw},0) rectangle ({\\cw*\\col + 0.85*\\cw},\\bhc);")
    lines.append("  \\node[axn,anchor=south] at ({\\cw*\\col + 0.5*\\cw},\\bhc) {\\ct};")
    lines.append("}")
    lines.append("")
    lines.append("% --- intersection matrix below (2 rows: \\linkerB, \\linkerC) ---")
    lines.append("\\foreach \\row/\\agent in {0/\\linkerB{},1/\\linkerC{}} {")
    lines.append("  \\node[label] at (-0.1,{-\\rh*\\row - 0.4}) {\\agent};")
    lines.append("  \\foreach \\col in {0,1,2} {")
    lines.append("    \\node[no-dot] at ({\\cw*\\col + 0.5*\\cw},{-\\rh*\\row - 0.4}) {};")
    lines.append("  }")
    lines.append("}")
    lines.append("% memberships:")
    lines.append("% col 0: only \\linkerB (Entity)")
    lines.append("\\node[dot] at ({\\cw*0 + 0.5*\\cw},-\\rh*0 - 0.4) {};")
    lines.append("% col 1: both")
    lines.append("\\node[dot] at ({\\cw*1 + 0.5*\\cw},-\\rh*0 - 0.4) {};")
    lines.append("\\node[dot] at ({\\cw*1 + 0.5*\\cw},-\\rh*1 - 0.4) {};")
    lines.append("\\draw[connect] ({\\cw*1 + 0.5*\\cw},-\\rh*0 - 0.4) -- ({\\cw*1 + 0.5*\\cw},-\\rh*1 - 0.4);")
    lines.append("% col 2: only \\linkerC (Coreference)")
    lines.append("\\node[dot] at ({\\cw*2 + 0.5*\\cw},-\\rh*1 - 0.4) {};")
    lines.append("")
    lines.append("\\node[font=\\scriptsize,anchor=south west,rotate=90] at (-1.0,0) {TPs in set};")
    lines.append("\\end{tikzpicture}")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{figure_label}}}")
    lines.append("\\end{figure}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(description="Emit RQ4 TeX figure + table (main + appendix).")
    parser.add_argument(
        "--csv-root",
        type=Path,
        default=Path("/mnt/hostshare/ardoco-home/agent-linker/results/v2.6.3"),
    )
    parser.add_argument(
        "--tex-out-main",
        type=Path,
        default=Path("/mnt/hostshare/ardoco-home/agent-linker/writing/working"),
    )
    parser.add_argument(
        "--tex-out-appendix",
        type=Path,
        default=Path("/mnt/hostshare/ardoco-home/agent-linker/writing/working/appendix"),
    )
    args = parser.parse_args()

    main_out = args.tex_out_main
    appendix_out = args.tex_out_appendix
    appendix_out.mkdir(parents=True, exist_ok=True)

    # Main body: Claude.
    claude_linkers = aggregate_backend_linker(args.csv_root, "claude")
    claude_upset = aggregate_backend_upset(args.csv_root, "claude")
    table_main = main_out / "table" / "rq4-agents.tex"
    fig_main = main_out / "figures" / "rq4-upset.tex"
    render_rq4_table(
        claude_linkers,
        overlap_value=claude_upset.get("both", 0),
        backend="claude",
        output_path=table_main,
        table_label="tab:rq4-agents",
    )
    render_rq4_upset(claude_upset, "claude", fig_main, "fig:rq4-upset")

    # Appendix: GPT-5.4 (openai).
    gpt_linkers = aggregate_backend_linker(args.csv_root, "openai")
    gpt_upset = aggregate_backend_upset(args.csv_root, "openai")
    table_app = appendix_out / "rq4-agents-gpt.tex"
    fig_app = appendix_out / "rq4-upset-gpt.tex"
    render_rq4_table(
        gpt_linkers,
        overlap_value=gpt_upset.get("both", 0),
        backend="openai",
        output_path=table_app,
        table_label="tab:rq4-agents-gpt",
    )
    render_rq4_upset(gpt_upset, "openai", fig_app, "fig:rq4-upset-gpt")

    print(
        f"[rq4-table] wrote main={table_main} {fig_main} "
        f"appendix={table_app} {fig_app}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
